USE stream;
INSERT INTO cards (nickname, mainCat, thematic, picture, name, language, pYoutube, pTwitch, pKick, pTwitter,
 pInstagram, pTiktok, videoOne, videoTwo, factOne, factTwo, factThree) VALUES
('Streamer1', 'Gaming', 'FPS', 'picture1.jpg', 'Nom1', 'Français', 'youtube.com/streamer1', 'twitch.tv/streamer1', 'kick.com/streamer1', 'twitter.com/streamer1', 'instagram.com/streamer1', 'tiktok.com/streamer1', 'video1_1.mp4', 'video1_2.mp4', 'Fait intéressant 1', 'Fait intéressant 2', 'Fait intéressant 3'),
('Streamer2', 'IRL', 'Vlog', 'picture2.jpg', 'Nom2', 'Anglais', 'youtube.com/streamer2', 'twitch.tv/streamer2', 'kick.com/streamer2', 'twitter.com/streamer2', 'instagram.com/streamer2', 'tiktok.com/streamer2', 'video2_1.mp4', 'video2_2.mp4', 'Fait intéressant 1', 'Fait intéressant 2', 'Fait intéressant 3'),
('Streamer3', 'Cooking', 'Food', 'picture3.jpg', 'Nom3', 'Espagnol', 'youtube.com/streamer3', 'twitch.tv/streamer3', 'kick.com/streamer3', 'twitter.com/streamer3', 'instagram.com/streamer3', 'tiktok.com/streamer3', 'video3_1.mp4', 'video3_2.mp4', 'Fait intéressant 1', 'Fait intéressant 2', 'Fait intéressant 3'),
('Streamer4', 'Musique', 'Art', 'picture4.jpg', 'Nom4', 'Italien', 'youtube.com/streamer4', 'twitch.tv/streamer4', 'kick.com/streamer4', 'twitter.com/streamer4', 'instagram.com/streamer4', 'tiktok.com/streamer4', 'video4_1.mp4', 'video4_2.mp4', 'Fait intéressant 1', 'Fait intéressant 2', 'Fait intéressant 3'),
('Streamer5', 'Fitness', 'Sport', 'picture5.jpg', 'Nom5', 'Allemand', 'youtube.com/streamer5', 'twitch.tv/streamer5', 'kick.com/streamer5', 'twitter.com/streamer5', 'instagram.com/streamer5', 'tiktok.com/streamer5', 'video5_1.mp4', 'video5_2.mp4', 'Fait intéressant 1', 'Fait intéressant 2', 'Fait intéressant 3'),
('Streamer6', 'Voyages', 'Tourisme', 'picture6.jpg', 'Nom6', 'Portugais', 'youtube.com/streamer6', 'twitch.tv/streamer6', 'kick.com/streamer6', 'twitter.com/streamer6', 'instagram.com/streamer6', 'tiktok.com/streamer6', 'video6_1.mp4', 'video6_2.mp4', 'Fait intéressant 1', 'Fait intéressant 2', 'Fait intéressant 3'),
('Streamer7', 'Beauté', 'Mode', 'picture7.jpg', 'Nom7', 'Français', 'youtube.com/streamer7', 'twitch.tv/streamer7', 'kick.com/streamer7', 'twitter.com/streamer7', 'instagram.com/streamer7', 'tiktok.com/streamer7', 'video7_1.mp4', 'video7_2.mp4', 'Fait intéressant 1', 'Fait intéressant 2', 'Fait intéressant 3');
