INSERT INTO cards (nickname, mainCat, thematic, picture, name, language, pYoutube, pTwitch, pKick, pTwitter,
 pInstagram, pTiktok, videoOne, videoTwo, factOne, factTwo, factThree) VALUES
('AkiWizard', 'Gaming', 'Divers', '_default_', '', 'Français', 'AkiWizard', 'akiwizard', 'akiwizard', 'AkiWizard', 'akiwizard', 'akiwizard', '', '', 'AkiWizard a contribué à construire le site Creator Deck !', '', ''),
('Amaru', 'Gaming', 'Divers', '_default_', 'Élias', 'Français', 'JLAmaru', 'amaru', '', 'EliasLeRetour', 'eliasleretour', 'eliasleretour', '', '', 'Amaru a co-fondé la Team JL (ou"Jobless") en 2019.', 'Il a été au cœur des polémiques autour du #BalanceTonInfluenceur, pour des cas de harcèlement sexuel.', ''),
('AmineMaTué', 'Gaming', 'Divers', '_default_', 'Mohammed Amine Mahmoud', 'Français', 'Aminematue', 'Aminematue', 'kick.com/streamer1', 'twitter.com/streamer1', 'instagram.com/streamer1', 'tiktok.com/streamer1', '', '', "AmineMaTué est l'organisateur du Eleven All-Stars, le match de football qui oppose streamers français et espagnols.", 'Le 19 novembre 2022, il bat le record de viewers simultanés sur Twitch (plus de 1,1 million), détenu auparavant par Sueezie (puis repris par celui-ci depuis).', ''),
('Anas_Off', 'Gaming', 'Divers', '_default_', '', 'Français', 'Anas170QI', 'anas_off', '', 'anas_offf', 'anas__officiel__', '', '', '', '', '', ''),
('AntoineDaniel', 'Gaming', 'Divers', 'antoinedaniel', 'Antoine Daniel', 'Français', 'BestOfAntoineDaniel', 'AntoineDaniel', '', '', 'mr.antoinedaniel', 'mr.antoinedaniel', '', '', '', '', ''),
('Bichouu_', 'Gaming', 'Divers', '_default_', '', 'Français', 'bichouu1334', 'bichouu_', '', 'jlbichouu', 'jlbichouu', '', '', '', '', '', ''),
('Chowh1', 'Gaming', 'FPS', '_default_', '', 'Français', 'ChowH1', 'chowh1', '', 'CHOWH1_', 'chowh1', 'chowh1', '', '', '', '', '');
